### ISSUE TITLE
Development / Integration of TTT_Totem into TTT2

### ISSUE THREAD

**Issue by Alf21** [GamefreakDE/TTT_Totem#4]
@saibotk Currently I'm developing [TTT2](https://github.com/Alf21/TTT2)? Now I wanna ask you whether you want to take part in this development. I suggest to give a look into the project and maybe add me in Steam if you want to. This could be useful to create a better TTT with a great compatibility and performance without these default bugs. (e.g. I planned to recreate the ScoreSystem as well as the role system).

**Comment by HagenKL** [comment]
I'm gonna think about it when I'm home from vacation. Already looked at your work and it's certainly not bad, and a cooperation would probably help to reduce bugs.

**Comment by saibotk** [comment]
At the moment i do not have enough time to do much, but it sure would be useful to do so
