### ISSUE TITLE
GetConVar(ttt_jackal_min_players):GetInt() (string expected, got nil)

### ISSUE THREAD

**Issue by xopez** [GamefreakDE/TTT_Totem#6]
Hello,

i want to make a rolerounter for jackal and co.
I wanted to retrieve the min players for jackal with GetConVar(ttt_jackal_min_players):GetInt() and got a nil value. i also want to get GetConVar(ttt_jackal_max):GetInt() with the same result. Am I doing something wrong with convar recieving?
It's an autorun-lua script.

**Comment by Alf21** [comment]
You are trying to put a variable in the function. Instead, use a string 
GetConVar(string) -> GetConVar("string")
Focus on the ' " '

So 
GetConVar(ttt_jackal_min_players):GetInt()
->
GetConVar("ttt_jackal_min_players"):GetInt()

**Comment by xopez** [comment]
Wow, i missed that
thanks for the help
