### ISSUE TITLE
Error client

### ISSUE THREAD

**Issue by dok441** [GamefreakDE/TTT_Totem#7]
[ERROR] addons/animations/lua/autorun/client/cl_buy_notif_autorun.lua:72: attempt to call method 'GetSubRoleData' (a nil value)
  1. func - addons/animations/lua/autorun/client/cl_buy_notif_autorun.lua:72
   2. unknown - lua/includes/extensions/net.lua:32

**Comment by saibotk** [comment]
This does not belong to Totem

**Comment by Alf21** [comment]
Wrong addon, try buy notification of saibotk ^^
